import React from "react";
import Header from "../../Component/AdminHeader/Header";
import "../../Style/report.css";
import CommisionBoardTable from "../../Component/Tables/CommisionBoardTable/CommisionBoardTable";

export default function CommisionBoard(){
    const data=[
        {
          date: "27-01-2022",
          companyName: "Steve",
          fundedAmount: "$20,000",
          upsell: "9%",
          lender: "Mr Advanced",
          cm: "$8,000",
          aup: "",
          split: "$900",
          remaining: "$900",
          agent: "Select",
          paid: "Yes",
          leader: "Select"
        },
        {
          date: "15-02-2022",
          companyName: "Marcelo",
          fundedAmount: "$2,50,000",
          upsell: "2%",
          lender: "Mr Advanced",
          cm: "$7,000",
          aup: "",
          split: "$2,500",
          remaining: "$2,500",
          agent: "SSMA Enterprise",
          paid: "Yes",
          leader: "Select"
        },
        {
          date: "15-02-2022",
          companyName: "Thomas",
          fundedAmount: "$45,000",
          upsell: "11%",
          lender: "Mr Advanced",
          cm: "$12.00",
          aup: "",
          split: "$1,733",
          remaining: "$3,200",
          agent: "SSMA Enterprise",
          paid: "Yes",
          leader: "Select"
        },
        {
          date: "15-02-2022",
          companyName: "Han",
          fundedAmount: "$90,000",
          upsell: "11%",
          lender: "NEWCO",
          cm: "$40.00",
          aup: "",
          split: "$4,950",
          remaining: "$4,950",
          agent: "Select",
          paid: "",
          leader: "Select"
        },
        {
          date: "16-02-2022",
          companyName: "Luke",
          fundedAmount: "$32,000",
          upsell: "11%",
          lender: "Mr Advanced",
          cm: "$90.00",
          aup: "",
          split: "$1,200",
          remaining: "$5,500",
          agent: "Select",
          paid: "Yes",
          leader: "Select"
        },
        {
          date: "17-02-2022",
          companyName: "Amanda",
          fundedAmount: "$1,00,000",
          upsell: "7%",
          lender: "NEWCO",
          cm: "$3,70,000",
          aup: "",
          split: "$7,500",
          remaining: "$0",
          agent: "Select",
          paid: "Clawback paid",
          leader: "Select"
        },
        {
          date: "15-03-2022",
          companyName: "Juan",
          fundedAmount: "$80,000",
          upsell: "11%",
          lender: "Splash",
          cm: "$30.00",
          aup: "",
          split: "$1,155",
          remaining: "$11,000",
          agent: "Magi Halabi",
          paid: "Clawback paid",
          leader: "Select"
        },
        {
          date: "15-03-2022",
          companyName: "Dylan",
          fundedAmount: "$95,000",
          upsell: "7%",
          lender: "Splash",
          cm: "$15.00",
          aup: "",
          split: "$1,425",
          remaining: "$1,600",
          agent: "Hermes Funding",
          paid: "Yes",
          leader: "Select"
        },
        {
          date: "25-03-2022",
          companyName: "Tessa",
          fundedAmount: "$87,000",
          upsell: "10%",
          lender: "Fox",
          cm: "$1,10,000",
          aup: "",
          split: "$9,000",
          remaining: "$1,800",
          agent: "Hermes Funding",
          paid: "Yes",
          leader: "Select"
        },
        {
          date: "15-03-2022",
          companyName: "Juan",
          fundedAmount: "$80,000",
          upsell: "11%",
          lender: "Splash",
          cm: "$30.00",
          aup: "",
          split: "$1,155",
          remaining: "$11,000",
          agent: "Magi Halabi",
          paid: "Clawback paid",
          leader: "Select"
        },
        {
          date: "15-03-2022",
          companyName: "Dylan",
          fundedAmount: "$95,000",
          upsell: "7%",
          lender: "Splash",
          cm: "$15.00",
          aup: "",
          split: "$1,425",
          remaining: "$1,600",
          agent: "Hermes Funding",
          paid: "Yes",
          leader: "Select"
        },
        {
          date: "25-03-2022",
          companyName: "Tessa",
          fundedAmount: "$87,000",
          upsell: "10%",
          lender: "Fox",
          cm: "$1,10,000",
          aup: "",
          split: "$9,000",
          remaining: "$1,800",
          agent: "Hermes Funding",
          paid: "Yes",
          leader: "Select"
        },
        {
          date: "15-03-2022",
          companyName: "Juan",
          fundedAmount: "$80,000",
          upsell: "11%",
          lender: "Splash",
          cm: "$30.00",
          aup: "",
          split: "$1,155",
          remaining: "$11,000",
          agent: "Magi Halabi",
          paid: "Clawback paid",
          leader: "Select"
        },
        {
          date: "15-03-2022",
          companyName: "Dylan",
          fundedAmount: "$95,000",
          upsell: "7%",
          lender: "Splash",
          cm: "$15.00",
          aup: "",
          split: "$1,425",
          remaining: "$1,600",
          agent: "Hermes Funding",
          paid: "Yes",
          leader: "Select"
        },
        {
          date: "25-03-2022",
          companyName: "Tessa",
          fundedAmount: "$87,000",
          upsell: "10%",
          lender: "Fox",
          cm: "$1,10,000",
          aup: "",
          split: "$9,000",
          remaining: "$1,800",
          agent: "Hermes Funding",
          paid: "Yes",
          leader: "Select"
        },
        {
          date: "15-03-2022",
          companyName: "Juan",
          fundedAmount: "$80,000",
          upsell: "11%",
          lender: "Splash",
          cm: "$30.00",
          aup: "",
          split: "$1,155",
          remaining: "$11,000",
          agent: "Magi Halabi",
          paid: "Clawback paid",
          leader: "Select"
        },
        {
          date: "15-03-2022",
          companyName: "Dylan",
          fundedAmount: "$95,000",
          upsell: "7%",
          lender: "Splash",
          cm: "$15.00",
          aup: "",
          split: "$1,425",
          remaining: "$1,600",
          agent: "Hermes Funding",
          paid: "Yes",
          leader: "Select"
        },
        {
          date: "25-03-2022",
          companyName: "Tessa",
          fundedAmount: "$87,000",
          upsell: "10%",
          lender: "Fox",
          cm: "$1,10,000",
          aup: "",
          split: "$9,000",
          remaining: "$1,800",
          agent: "Hermes Funding",
          paid: "Yes",
          leader: "Select"
        },
        {
          date: "15-03-2022",
          companyName: "Juan",
          fundedAmount: "$80,000",
          upsell: "11%",
          lender: "Splash",
          cm: "$30.00",
          aup: "",
          split: "$1,155",
          remaining: "$11,000",
          agent: "Magi Halabi",
          paid: "Clawback paid",
          leader: "Select"
        },
        {
          date: "15-03-2022",
          companyName: "Dylan",
          fundedAmount: "$95,000",
          upsell: "7%",
          lender: "Splash",
          cm: "$15.00",
          aup: "",
          split: "$1,425",
          remaining: "$1,600",
          agent: "Hermes Funding",
          paid: "Yes",
          leader: "Select"
        },
        {
          date: "25-03-2022",
          companyName: "Tessa",
          fundedAmount: "$87,000",
          upsell: "10%",
          lender: "Fox",
          cm: "$1,10,000",
          aup: "",
          split: "$9,000",
          remaining: "$1,800",
          agent: "Hermes Funding",
          paid: "Yes",
          leader: "Select"
        },
        {
          date: "15-03-2022",
          companyName: "Juan",
          fundedAmount: "$80,000",
          upsell: "11%",
          lender: "Splash",
          cm: "$30.00",
          aup: "",
          split: "$1,155",
          remaining: "$11,000",
          agent: "Magi Halabi",
          paid: "Clawback paid",
          leader: "Select"
        },
        {
          date: "15-03-2022",
          companyName: "Dylan",
          fundedAmount: "$95,000",
          upsell: "7%",
          lender: "Splash",
          cm: "$15.00",
          aup: "",
          split: "$1,425",
          remaining: "$1,600",
          agent: "Hermes Funding",
          paid: "Yes",
          leader: "Select"
        },
        {
          date: "25-03-2022",
          companyName: "Tessa",
          fundedAmount: "$87,000",
          upsell: "10%",
          lender: "Fox",
          cm: "$1,10,000",
          aup: "",
          split: "$9,000",
          remaining: "$1,800",
          agent: "Hermes Funding",
          paid: "Yes",
          leader: "Select"
        },
        {
          date: "15-03-2022",
          companyName: "Juan",
          fundedAmount: "$80,000",
          upsell: "11%",
          lender: "Splash",
          cm: "$30.00",
          aup: "",
          split: "$1,155",
          remaining: "$11,000",
          agent: "Magi Halabi",
          paid: "Clawback paid",
          leader: "Select"
        },
        {
          date: "15-03-2022",
          companyName: "Dylan",
          fundedAmount: "$95,000",
          upsell: "7%",
          lender: "Splash",
          cm: "$15.00",
          aup: "",
          split: "$1,425",
          remaining: "$1,600",
          agent: "Hermes Funding",
          paid: "Yes",
          leader: "Select"
        },
        {
          date: "25-03-2022",
          companyName: "Tessa",
          fundedAmount: "$87,000",
          upsell: "10%",
          lender: "Fox",
          cm: "$1,10,000",
          aup: "",
          split: "$9,000",
          remaining: "$1,800",
          agent: "Hermes Funding",
          paid: "Yes",
          leader: "Select"
        }
        
      ];
    return(
        <>
            <div className="commisionBoardContainer">
                <Header/>
                <CommisionBoardTable data={data}/>
            </div>
        </>
    );
}